version: 0.2

env:
  variables:
    LW_SCANNER_VERSION: v0.27.9 # renovate: depName=lacework/lacework-vulnerability-scanner

phases:
  install:
    commands:
      - curl -sL https://github.com/lacework/lacework-vulnerability-scanner/releases/download/${LW_SCANNER_VERSION}/lw-scanner-linux-amd64 -o lw-scanner
      - pip3 install mkdocs-techdocs-core==1.6.0
