# Source: linkerd2/templates/heartbeat.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linkerd-heartbeat
  namespace: linkerd
  labels:
    app.kubernetes.io/name: heartbeat
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: stable-2.11.2
    linkerd.io/control-plane-component: heartbeat
    linkerd.io/control-plane-ns: linkerd
  annotations:
    linkerd.io/created-by: linkerd/helm stable-2.11.2
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            linkerd.io/control-plane-component: heartbeat
            linkerd.io/workload-ns: linkerd
          annotations:
            linkerd.io/created-by: linkerd/helm stable-2.11.2
        spec:
          restartPolicy: Never
          serviceAccountName: linkerd-heartbeat
          nodeSelector:
            kubernetes.io/os: linux
          containers:
          - name: heartbeat
            image: cr.l5d.io/linkerd/controller:stable-2.11.2
            args:
            - "heartbeat"
            - "-controller-namespace=linkerd"
            - "-log-level=info"
            - "-log-format=plain"
            - "-prometheus-url=http://prometheus.linkerd-viz.svc.cluster.local:9090"
            env:
            - name: LINKERD_DISABLED
              value: "the heartbeat controller does not use the proxy"
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsUser: 2103
  schedule: "21 00 * * *"
  successfulJobsHistoryLimit: 0
